### ISSUE TITLE
Spectate is still broken

### ISSUE THREAD

**Issue by Vilusia** [ForrestMarkX/glua-ZombieMaster#1]
Spectating is still broken, You get stuck in walls and can't move.

**Comment by ForrestMarkX** [comment]
I can not reproduce this issue

**Comment by Vilusia** [comment]
Go into a room and die. You will get stuck in the roof/wall. It's happened numerous times.

**Comment by ForrestMarkX** [comment]
Addressed in commit 26f9c37616452362114ba4c109cdf6cdf787bb9e
