### ISSUE TITLE
No Sprinting?

### ISSUE THREAD

**Issue by ash47** [ForrestMarkX/glua-ZombieMaster#3]
Can you add a convar to allow (and change the speed of) sprinting?

I haven't played Zombie Master in years, I can't remember if there is sprinting or not, however, just walking around in this feels really painful to me.

Although not directly related to this, are you open to others contributing code? Are there any guidelines?

**Comment by ForrestMarkX** [comment]
Sadly no, Zombie Master didn't have sprinting and adding it would make alot of maps impossible for the ZM. Code contributing is fine by me as long as it does not change the core gameplay

**Comment by ash47** [comment]
Is this a case of the Zombies simply can't catch the humans? Or is this something like the humans can reach platforms that would previously be unreachable?

**Comment by ForrestMarkX** [comment]
Both
