### ISSUE TITLE
Deathrun Maps?

### ISSUE THREAD

**Issue by ash47** [ForrestMarkX/glua-ZombieMaster#4]
Would you ever considering allowing Deathrun Maps?

This is something I can contribute easily (you wouldn't really have to do anything), specifically, there is `gamemode/maps/*.lua`, these contain edits for maps.

Using those Lua edit files, it would be quite easy to take death run maps and map them out so that the Zombie Master can activate the traps instead of the deaths.

Is this something you would consider merging, or is this going too far away from what Zombie Master is meant to be?

**Comment by ForrestMarkX** [comment]
Yes I can add something like that, would make ZM more refreshing with it's Deathrun maps
